// ─── < Imports > ────────────────────────────────────────────────────

use anyhow::{Context, Result};

use std::{
    env, fs,
    path::{Path, PathBuf},
};

use crate::{fs::atomic_write, palette::Palette};

// ─── < Constants > ──────────────────────────────────────────────────

const GENERATED_HEADER: &str = "// Generated by hyprcolor. Manual changes will be overwritten.\n\n";

// ─── < Public Functions > ───────────────────────────────────────────

pub fn export(palette: &Palette) -> Result<()> {
    let config_file = fastfetch_config_file();

    if let Some(parent) = config_file.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("no se pudo crear directorio de fastfetch {}", parent.display()))?;
    }

    backup_manual_config(&config_file)?;

    let content = config_content(palette)?;
    atomic_write(&config_file, content).with_context(|| format!("no se pudo escribir {}", config_file.display()))?;

    Ok(())
}

// ─── < Private Functions > ──────────────────────────────────────────

// ─── < Config Content > ────

fn config_content(palette: &Palette) -> Result<String> {
    let logo_path = current_wallpaper_image_path().unwrap_or_else(|| {
        palette
            .wallpaper
            .canonicalize()
            .unwrap_or_else(|_| palette.wallpaper.clone())
    });

    let logo_source = logo_path.to_string_lossy().to_string();

    let ui_accent = fastfetch_color(&palette.ui_accent);
    let separator_color = fastfetch_color(&palette.surface_variant);
    let output_color = fastfetch_color(&palette.foreground);

    let title = title_format(&palette.ui_accent);
    let palette_row = palette_swatch_format(palette);

    let config = serde_json::json!({
        "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",

        "logo": {
            "type": "kitty",
            "source": logo_source,
            "width": 40,
            "height": 11,
            "preserveAspectRatio": true,
            "padding": {
                "right": 3
            }
        },

        "display": {
            "separator": "  ",
            "key": {
                "width": 12,
                "type": "string"
            },
            "color": {
                "keys": ui_accent,
                "title": ui_accent,
                "separator": separator_color,
                "output": output_color
            }
        },

        "modules": [
            {
                "type": "custom",
                "key": " ",
                "format": title
            },
            "separator",

            fastfetch_module("os", "  OS", &ui_accent, &output_color),
            fastfetch_module("kernel", "  Kernel", &ui_accent, &output_color),
            fastfetch_module("wm", "  WM", &ui_accent, &output_color),
            fastfetch_module("shell", "  Shell", &ui_accent, &output_color),
            fastfetch_module("terminal", "  Term", &ui_accent, &output_color),

            "break",

            fastfetch_module("cpu", "  CPU", &ui_accent, &output_color),
            fastfetch_module("gpu", "󰢮  GPU", &ui_accent, &output_color),
            fastfetch_module("memory", "  RAM", &ui_accent, &output_color),
            fastfetch_module("disk", "  Disk", &ui_accent, &output_color),

            "break",

            fastfetch_module("localip", "󰩟  IP", &ui_accent, &output_color),
            fastfetch_module("uptime", "󰔚  Up", &ui_accent, &output_color),

            "break",

            {
                "type": "custom",
                "key": " ",
                "format": palette_row
            }
        ]
    });

    let config = serde_json::to_string_pretty(&config).context("no se pudo serializar config de fastfetch")?;

    Ok(format!("{GENERATED_HEADER}{config}\n"))
}

// ─── < Fastfetch Module > ────

fn fastfetch_module(module_type: &str, key: &str, key_color: &str, output_color: &str) -> serde_json::Value {
    serde_json::json!({
        "type": module_type,
        "key": key,
        "keyColor": key_color,
        "outputColor": output_color
    })
}

// ─── < Title Format > ────

fn title_format(accent: &str) -> String {
    let title = format!("{}@{}", current_user(), current_host());

    match inline_color(accent) {
        Some(color) => format!("{color}{title}{{#}}"),
        None => title,
    }
}

// ─── < Current User > ────

fn current_user() -> String {
    env::var("USER").unwrap_or_else(|_| "user".to_string())
}

// ─── < Current Host > ────

fn current_host() -> String {
    env::var("HOSTNAME")
        .ok()
        .filter(|host| !host.trim().is_empty())
        .or_else(|| {
            fs::read_to_string("/etc/hostname")
                .ok()
                .map(|host| host.trim().to_string())
                .filter(|host| !host.is_empty())
        })
        .unwrap_or_else(|| "host".to_string())
}

// ─── < Palette Swatch Format > ────

fn palette_swatch_format(palette: &Palette) -> String {
    hyprcolor_palette_colors(palette)
        .into_iter()
        .take(8)
        .map(|color| filled_swatch(&color))
        .collect::<Vec<_>>()
        .join("  ")
}

// ─── < Hyprcolor Palette Colors > ────

fn hyprcolor_palette_colors(palette: &Palette) -> Vec<String> {
    if !palette.swatches.is_empty() {
        return palette.swatches.clone();
    }

    vec![
        palette.accent.clone(),
        palette.accent_1.clone(),
        palette.accent_2.clone(),
        palette.accent_3.clone(),
        palette.surface_variant.clone(),
        palette.surface.clone(),
        palette.background.clone(),
        palette.foreground.clone(),
    ]
}

// ─── < Filled Swatch > ────

fn filled_swatch(hex: &str) -> String {
    match inline_color(hex) {
        Some(color) => format!("{color}{{#}}"),
        None => "".to_string(),
    }
}

// ─── < Fastfetch Color > ────

fn fastfetch_color(hex: &str) -> String {
    normalize_hex_color(hex).unwrap_or_else(|| "default".to_string())
}

// ─── < Inline Color > ────

fn inline_color(hex: &str) -> Option<String> {
    let hex = normalize_hex_color(hex)?;
    let hex = hex.trim_start_matches('#');

    Some(format!("{{##{hex}}}"))
}

// ─── < Normalize Hex Color > ────

fn normalize_hex_color(hex: &str) -> Option<String> {
    let (r, g, b) = parse_hex_color(hex)?;
    Some(format!("#{:02x}{:02x}{:02x}", r, g, b))
}

// ─── < Parse Hex Color > ────

fn parse_hex_color(hex: &str) -> Option<(u8, u8, u8)> {
    let hex = hex.trim().trim_start_matches('#');

    if hex.len() != 6 {
        return None;
    }

    let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
    let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
    let b = u8::from_str_radix(&hex[4..6], 16).ok()?;

    Some((r, g, b))
}

// ─── < Backup Manual Config > ────

fn backup_manual_config(config_file: &Path) -> Result<()> {
    let Ok(existing) = fs::read_to_string(config_file) else {
        return Ok(());
    };

    if existing.starts_with(GENERATED_HEADER) {
        return Ok(());
    }

    let backup_file = config_file.with_file_name("config.jsonc.backup");

    if backup_file.exists() {
        return Ok(());
    }

    fs::write(&backup_file, existing).with_context(|| format!("no se pudo crear backup {}", backup_file.display()))?;

    Ok(())
}

// ─── < Fastfetch Config File > ────

fn fastfetch_config_file() -> PathBuf {
    if let Some(config_home) = env::var_os("XDG_CONFIG_HOME") {
        return PathBuf::from(config_home).join("fastfetch").join("config.jsonc");
    }

    env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config")
        .join("fastfetch")
        .join("config.jsonc")
}

// ─── < Current Wallpaper Image Path > ────

fn current_wallpaper_image_path() -> Option<PathBuf> {
    if let Some(cache_home) = env::var_os("XDG_CACHE_HOME") {
        return Some(
            PathBuf::from(cache_home)
                .join("hyprwall")
                .join("current_wallpaper_image"),
        );
    }

    env::var_os("HOME").map(|home| {
        PathBuf::from(home)
            .join(".cache")
            .join("hyprwall")
            .join("current_wallpaper_image")
    })
}
