use anyhow::Result;
use std::{env, fs, path::PathBuf, process::Command};

use crate::{fs::atomic_write, palette::Palette};

pub fn export(palette: &Palette) -> Result<()> {
    let path = ghostty_colors_file();

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    atomic_write(&path, build_config(palette))?;

    let _ = Command::new("pkill").args(["-USR1", "ghostty"]).output();

    Ok(())
}

fn build_config(palette: &Palette) -> String {
    let ansi = ansi_palette(palette);
    let mut out = String::from("# Generated by hyprcolor — do not edit manually\n\n");

    out.push_str("background = #000000\n"); // ← negro fijo
    out.push_str(&format!("foreground = {}\n", palette.foreground));
    out.push_str(&format!("cursor-color = {}\n", palette.ui_accent));
    out.push_str(&format!("selection-background = {}\n", palette.surface_variant));
    out.push_str(&format!("selection-foreground = {}\n\n", palette.foreground));

    for (i, color) in ansi.iter().enumerate() {
        out.push_str(&format!("palette = {}={}\n", i, color));
    }
    out.push('\n');
    out
}

fn ansi_palette(palette: &Palette) -> Vec<String> {
    let swatches: Vec<String> = if palette.swatches.len() >= 4 {
        palette.swatches[..4].to_vec()
    } else {
        vec![
            palette.accent.clone(),
            palette.accent_1.clone(),
            palette.accent_2.clone(),
            palette.accent_3.clone(),
        ]
    };

    vec![
        palette.background.clone(),
        "#f38ba8".to_string(),
        "#a6e3a1".to_string(),
        swatches[0].clone(),
        swatches[1].clone(),
        swatches[2].clone(),
        swatches[3].clone(),
        palette.foreground.clone(),
        palette.surface_variant.clone(),
        "#f38ba8".to_string(),
        "#a6e3a1".to_string(),
        lighten(&swatches[0], 0.18),
        lighten(&swatches[1], 0.18),
        lighten(&swatches[2], 0.18),
        lighten(&swatches[3], 0.18),
        palette.foreground.clone(),
    ]
}

fn lighten(hex: &str, amount: f32) -> String {
    let hex = hex.trim_start_matches('#');
    if hex.len() != 6 {
        return format!("#{hex}");
    }
    let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(128);
    let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(128);
    let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(128);
    let l = |c: u8| -> u8 { (c as f32 + (255.0 - c as f32) * amount).min(255.0) as u8 };
    format!("#{:02x}{:02x}{:02x}", l(r), l(g), l(b))
}

fn ghostty_colors_file() -> PathBuf {
    if let Some(xdg) = env::var_os("XDG_CONFIG_HOME") {
        return PathBuf::from(xdg).join("ghostty").join("hyprcolor");
    }
    env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config/ghostty/hyprcolor")
}
