use anyhow::Result;
use std::path::Path;

use crate::{fs::atomic_write, palette::Palette};

pub fn export(output_dir: &Path, palette: &Palette) -> Result<()> {
    atomic_write(output_dir.join("colors.zsh"), build_config(palette))
}

fn build_config(palette: &Palette) -> String {
    let mut out = String::from("# Generated by hyprcolor — do not edit manually\n\n");

    out.push_str(&format!("export HYPRCOLOR_BACKGROUND=\"{}\"\n", palette.background));
    out.push_str(&format!("export HYPRCOLOR_FOREGROUND=\"{}\"\n", palette.foreground));
    out.push_str(&format!("export HYPRCOLOR_ACCENT=\"{}\"\n", palette.accent));
    out.push_str(&format!("export HYPRCOLOR_ACCENT_1=\"{}\"\n", palette.accent_1));
    out.push_str(&format!("export HYPRCOLOR_ACCENT_2=\"{}\"\n", palette.accent_2));
    out.push_str(&format!("export HYPRCOLOR_ACCENT_3=\"{}\"\n", palette.accent_3));
    out.push_str(&format!("export HYPRCOLOR_SURFACE=\"{}\"\n", palette.surface));
    out.push_str(&format!("export HYPRCOLOR_SURFACE_VARIANT=\"{}\"\n\n", palette.surface_variant));

    out.push_str("# zsh-syntax-highlighting\n");
    out.push_str("ZSH_HIGHLIGHT_STYLES[command]=\"fg=#a6e3a1,bold\"\n");
    out.push_str("ZSH_HIGHLIGHT_STYLES[unknown-token]=\"fg=#f38ba8\"\n");
    out.push_str(&format!("ZSH_HIGHLIGHT_STYLES[alias]=\"fg={},bold\"\n", palette.accent));
    out.push_str(&format!("ZSH_HIGHLIGHT_STYLES[builtin]=\"fg={}\"\n", palette.accent_1));
    out.push_str(&format!("ZSH_HIGHLIGHT_STYLES[function]=\"fg={}\"\n", palette.accent_2));
    out.push_str(&format!("ZSH_HIGHLIGHT_STYLES[path]=\"fg={},underline\"\n", palette.foreground));
    out.push_str(&format!("ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=\"fg={}\"\n", palette.accent_3));
    out.push_str(&format!("ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=\"fg={}\"\n", palette.accent_3));
    out.push_str(&format!("ZSH_HIGHLIGHT_STYLES[comment]=\"fg={}\"\n", palette.surface_variant));
    out.push_str(&format!("ZSH_HIGHLIGHT_STYLES[globbing]=\"fg={}\"\n\n", palette.accent_2));

    out.push_str("# zsh-autosuggestions\n");
    out.push_str(&format!("ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=\"fg={}\"\n\n", palette.surface_variant));

    out
}
